### ISSUE TITLE
`mockIonCheckbox` throws an error when `onIonFocus` or `onIonBlur` is provided

### ISSUE THREAD

**Issue by coreyjv** [ionic-team/ionic-react-test-utils#15]
When executing tests that use the `IonToggle` component `mockIonCheckbox` logs the following error:

```
console.error
      Warning: Unknown event handler property `onIonFocus`. It will be ignored.
          at input
          at Object.<anonymous>.exports.mockIonCheckbox (/node_modules/@ionic/react-test-utils/src/mocks/mockIonCheckbox.tsx:7:7)

console.error
      Warning: Unknown event handler property `onIonBlur`. It will be ignored.
          at input
          at Object.<anonymous>.exports.mockIonCheckbox (/node_modules/@ionic/react-test-utils/src/mocks/mockIonCheckbox.tsx:7:7)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at validateProperty$1 (node_modules/react-dom/cjs/react-dom.development.js:3448:9)
      at warnUnknownProperties (node_modules/react-dom/cjs/react-dom.development.js:3559:21)
      at validateProperties$2 (node_modules/react-dom/cjs/react-dom.development.js:3583:3)
      at validatePropertiesInDevelopment (node_modules/react-dom/cjs/react-dom.development.js:8765:5)
      at setInitialProperties (node_modules/react-dom/cjs/react-dom.development.js:9041:5)
      at finalizeInitialChildren (node_modules/react-dom/cjs/react-dom.development.js:10201:3)
```

**Comment by elylucas** [comment]
Thanks for the PR @coreyjv

**Comment by coreyjv** [comment]
No problem!
