### ISSUE TITLE
Imposibility of testing IonInput

### ISSUE THREAD

**Issue by FernetB** [ionic-team/ionic-react-test-utils#29]
Hi folks!

Currently i'm trying to test an `IonInput` but seems impossible.

```
test('input to be writable', () => {
    render(
    <Input title="input xd" value="this is a value" placeholder="ingrese"/>
    )

    const ionInput = screen.getByTitle('input xd');
    
    expect(ionInput).toBeInTheDocument();

    fireEvent.ionFocus(ionInput);
    fireEvent.ionChange(ionInput, {target: {value: "new value"}})

    expect(ionInput.value).toBe("new value"); <- ionInput.value always undefined
})
```

If this is because the value is stored on the `<input />` then is impossible to get because jest does not know that there is an input on the dom

this -> `const input = screen.getByRole('input')` always return an error

**Comment by cuzzlor** [comment]
I'm guessing the error is what we get because pretty-format cannot print the DOM or whatever it does:

```
 RangeError: Invalid string length

      at printObjectProperties (node_modules/pretty-format/build/collections.js:174:47)
      at printComplexValue (node_modules/pretty-format/build/index.js:310:48)
```
